// A DOM node that has been generated by the parser.
pub struct Node<'a> {
    value: &'a str,
    children: Vec<Node<'a>>,
}

impl<'a> Node<'a> {
    pub fn new(value: &'a str) -> Self {
        Node {
            value,
            children: Vec::new(),
        }
    }

    pub fn add_child(&mut self, child: Node<'a>) {
        self.children.push(child)
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_nodes() {
        let mut n = Node::new("foo");
        assert_eq!(n.value, "foo");
        assert_eq!(n.children.len(), 0);

        let n2 = Node::new("bar");
        let n3 = Node::new("baz");
        n.add_child(n2);
        n.add_child(n3);
        assert_eq!(n.children.len(), 2);

        assert_eq!(n.children[0].value, "bar");
        assert_eq!(n.children[0].children.len(), 0);

        assert_eq!(n.children[1].value, "baz");
        assert_eq!(n.children[1].children.len(), 0);
    }
}