// A DOM node that has been generated by the parser.
pub struct Node {
    value: String,
    children: Vec<Node>,
}

impl Node {
    pub fn new(value: String) -> Self {
        Node {
            value,
            children: Vec::new()
        }
    }

    pub fn add_node(&mut self, n: Node) {
        self.children.push(n)
    }
}