//! The offline mode that turns the checked-in definitions into one keyword enum per property whose
//! grammar is a plain choice of keywords.
//!
//! The typed style used to map each such property by hand, matching strings against a grammar
//! nothing checked it against: a keyword the grammar accepts could land on the match's `_ =>`
//! arm and quietly become another value. With an enum per property, generated from the same
//! grammar, the hand-written mapping is an exhaustive `match` - a keyword added to the grammar is
//! a compile error until someone decides what it means.
//!
//! Only grammars that are keywords all the way down get an enum: `a | b | c`, where each
//! alternative is a keyword or a named type (`<line-style>`) that is itself such a choice.
//! Anything with a number, a length, a function or a combination (`[ a || b ]`) is mixed, and its
//! reader stays hand-written.

use anyhow::{Context, Result};
use std::collections::HashMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use crate::types::Property;

/// The keywords a grammar is a plain choice of, following named types; `None` when it is not one.
fn keywords_of(syntax: &str, values: &HashMap<String, String>, depth: usize) -> Option<Vec<String>> {
    if depth > 8 {
        return None;
    }
    let mut keywords = Vec::new();
    for alternative in syntax.split('|').map(str::trim) {
        if let Some(name) = alternative.strip_prefix('<').and_then(|rest| rest.strip_suffix('>')) {
            // A quoted reference (`<'color'>`) names a property, and a range (`<number [0,1]>`)
            // a datatype; neither is a named keyword set.
            if name.starts_with('\'') || name.contains(' ') {
                return None;
            }
            let inner = values.get(&format!("<{name}>"))?;
            keywords.extend(keywords_of(inner, values, depth + 1)?);
        } else if !alternative.is_empty()
            && alternative
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
            && !alternative.starts_with(|c: char| c.is_ascii_digit())
        {
            keywords.push(alternative.to_string());
        } else {
            return None;
        }
    }
    // The CSS-wide keywords some grammars spell out are the cascade's, not the property's.
    keywords.retain(|keyword| !matches!(keyword.as_str(), "initial" | "inherit" | "unset"));
    let mut seen = Vec::new();
    keywords.retain(|keyword| {
        let new = !seen.contains(keyword);
        seen.push(keyword.clone());
        new
    });
    Some(keywords)
}

/// The Rust name for a CSS name: its hyphen-separated words in UpperCamelCase, a vendor prefix's
/// empty leading word dropped (`-webkit-center` is `WebkitCenter`).
fn camel(name: &str) -> String {
    let mut out = String::new();
    for word in name.split('-').filter(|word| !word.is_empty()) {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn render(sets: &[(String, Vec<String>)]) -> String {
    let mut out = String::new();
    out.push_str(
        "//! Generated by `cargo run -p generate_definitions -- --keywords` from the checked-in\n\
         //! definitions. Do not edit; regenerate after the definition JSON changes.\n\
         //!\n\
         //! One enum per property whose grammar is a plain choice of keywords. See the generator's\n\
         //! `keywords` module for which grammars qualify.\n\n\
         use cow_utils::CowUtils;\n\n\
         /// A property's keywords, read from a value the grammar already accepted.\n\
         pub trait Keyword: Sized + Copy + 'static {\n\
         \x20   /// Every keyword, in the grammar's order.\n\
         \x20   const ALL: &'static [Self];\n\
         \x20   /// The keyword `ident` spells, ASCII case-insensitively; `None` for one it does not.\n\
         \x20   fn from_ident(ident: &str) -> Option<Self>;\n\
         \x20   /// The keyword as the grammar spells it.\n\
         \x20   fn name(self) -> &'static str;\n\
         }\n",
    );
    out.push_str(
        "\n/// Every property with a keyword enum, and its keywords as the grammar spells them. A test\n\
         /// compares this with the grammar the engine runs, so a stale regeneration fails.\n\
         pub const KEYWORD_SETS: &[(&str, &[&str])] = &[\n",
    );
    for (property, keywords) in sets {
        let list = keywords
            .iter()
            .map(|k| format!("\"{k}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    (\"{property}\", &[{list}]),");
    }
    out.push_str("];\n");
    for (property, keywords) in sets {
        let ty = format!("{}Keyword", camel(property));
        let _ = writeln!(out, "\n/// The keywords of `{property}`.");
        out.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
        let _ = writeln!(out, "pub enum {ty} {{");
        for keyword in keywords {
            let _ = writeln!(out, "    {},", camel(keyword));
        }
        out.push_str("}\n\n");
        let _ = writeln!(out, "impl Keyword for {ty} {{");
        out.push_str("    const ALL: &'static [Self] = &[\n");
        for keyword in keywords {
            let _ = writeln!(out, "        Self::{},", camel(keyword));
        }
        out.push_str("    ];\n\n");
        out.push_str("    fn from_ident(ident: &str) -> Option<Self> {\n");
        out.push_str("        Some(match ident.cow_to_ascii_lowercase().as_ref() {\n");
        for keyword in keywords {
            let _ = writeln!(out, "            \"{keyword}\" => Self::{},", camel(keyword));
        }
        out.push_str("            _ => return None,\n        })\n    }\n\n");
        out.push_str("    fn name(self) -> &'static str {\n        match self {\n");
        for keyword in keywords {
            let _ = writeln!(out, "            Self::{} => \"{keyword}\",", camel(keyword));
        }
        out.push_str("        }\n    }\n}\n");
    }
    out
}

/// Read the properties and values files and write the keyword module.
pub fn generate(properties_path: &Path, values_path: &Path, output: &Path) -> Result<()> {
    let text = fs::read_to_string(properties_path).with_context(|| format!("reading {}", properties_path.display()))?;
    let properties: Vec<Property> =
        serde_json::from_str(&text).with_context(|| format!("parsing {}", properties_path.display()))?;
    let text = fs::read_to_string(values_path).with_context(|| format!("reading {}", values_path.display()))?;
    let raw: Vec<serde_json::Value> =
        serde_json::from_str(&text).with_context(|| format!("parsing {}", values_path.display()))?;
    let values: HashMap<String, String> = raw
        .iter()
        .filter_map(|entry| {
            Some((
                entry["name"].as_str()?.to_string(),
                entry["syntax"].as_str()?.to_string(),
            ))
        })
        .collect();

    let mut sets: Vec<(String, Vec<String>)> = properties
        .iter()
        // Shorthands are expanded before anything reads them, and custom properties have no
        // grammar of their own.
        // `all` is nothing but the CSS-wide keywords, which the cascade handles itself.
        .filter(|property| property.computed.len() <= 1 && !property.name.starts_with("--") && property.name != "all")
        .filter_map(|property| Some((property.name.clone(), keywords_of(&property.syntax, &values, 0)?)))
        .collect();
    sets.sort_by(|a, b| a.0.cmp(&b.0));

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output, render(&sets))?;
    eprintln!("wrote {} ({} keyword properties)", output.display(), sets.len());
    Ok(())
}
