use crate::types::{BorderCollapse, CssProp, CssLength, TableRole, TableSizing};
use crate::TableTree;

/// Fully parsed table structure, typed by section kind.
pub struct TableModel<N> {
    pub node: N,
    pub caption: Option<N>,
    pub column_groups: Vec<ColGroup<N>>,
    /// Rows from `<thead>` / `display: table-header-group` elements, in source order.
    pub header_groups: Vec<RowGroup<N>>,
    /// Rows from `<tbody>` / `display: table-row-group` elements, in source order.
    pub row_groups: Vec<RowGroup<N>>,
    /// Rows from `<tfoot>` / `display: table-footer-group` elements, in source order.
    pub footer_groups: Vec<RowGroup<N>>,
    pub sizing: TableSizing,
    pub border_collapse: BorderCollapse,
    /// `border-spacing` horizontal and vertical values in pixels.
    pub border_spacing: (f32, f32),
}

pub struct ColGroup<N> {
    pub node: N,
    pub columns: Vec<N>,
}

pub struct RowGroup<N> {
    /// `None` for anonymous groups generated by the algorithm.
    pub node: Option<N>,
    pub rows: Vec<TableRow<N>>,
}

pub struct TableRow<N> {
    /// `None` for anonymous rows generated by the algorithm.
    pub node: Option<N>,
    pub cells: Vec<SourceCell<N>>,
}

/// A cell as read directly from the source tree, before grid placement.
pub struct SourceCell<N> {
    pub node: N,
    /// Effective colspan (always >= 1).
    pub colspan: usize,
    /// Effective rowspan (always >= 1, clamped per section by the grid builder).
    pub rowspan: usize,
}

/// Walk `tree` starting from `table_node` and build the typed `TableModel`.
///
/// Anonymous row groups and rows are generated where the CSS spec requires them
/// (§17.2.1): a bare `Row` directly under the table becomes a body row group;
/// a bare `Cell` directly under a row group becomes an anonymous row.
pub fn build_model<T: TableTree>(tree: &T, table_node: T::NodeId) -> TableModel<T::NodeId> {
    let mut model = TableModel {
        node: table_node,
        caption: None,
        column_groups: Vec::new(),
        header_groups: Vec::new(),
        row_groups: Vec::new(),
        footer_groups: Vec::new(),
        sizing: parse_table_sizing(tree, table_node),
        border_collapse: parse_border_collapse(tree, table_node),
        border_spacing: parse_border_spacing(tree, table_node),
    };

    for child in tree.children(table_node) {
        match tree.table_role(child) {
            TableRole::Caption => {
                if model.caption.is_none() {
                    model.caption = Some(child);
                }
            }
            TableRole::ColumnGroup => {
                model.column_groups.push(build_col_group(tree, child));
            }
            TableRole::HeaderGroup => {
                model.header_groups.push(build_row_group(tree, child));
            }
            TableRole::RowGroup => {
                model.row_groups.push(build_row_group(tree, child));
            }
            TableRole::FooterGroup => {
                model.footer_groups.push(build_row_group(tree, child));
            }
            // Bare row directly inside the table → anonymous tbody
            TableRole::Row => {
                let group = anon_body_group(&mut model.row_groups);
                group.rows.push(build_row(tree, child));
            }
            // Bare cell directly inside the table → anonymous row inside anonymous tbody
            TableRole::Cell => {
                let group = anon_body_group(&mut model.row_groups);
                let row = anon_row(&mut group.rows);
                row.cells.push(build_source_cell(tree, child));
            }
            // Column, Other — not direct children of the table box
            TableRole::Table
            | TableRole::Column
            | TableRole::Other => {}
        }
    }

    model
}

fn build_col_group<T: TableTree>(tree: &T, node: T::NodeId) -> ColGroup<T::NodeId> {
    let mut group = ColGroup { node, columns: Vec::new() };
    for child in tree.children(node) {
        if tree.table_role(child) == TableRole::Column {
            group.columns.push(child);
        }
    }
    group
}

fn build_row_group<T: TableTree>(tree: &T, node: T::NodeId) -> RowGroup<T::NodeId> {
    let mut group = RowGroup { node: Some(node), rows: Vec::new() };
    for child in tree.children(node) {
        match tree.table_role(child) {
            TableRole::Row => group.rows.push(build_row(tree, child)),
            // Cell directly inside row group → anonymous row
            TableRole::Cell => {
                let row = anon_row(&mut group.rows);
                row.cells.push(build_source_cell(tree, child));
            }
            _ => {}
        }
    }
    group
}

fn build_row<T: TableTree>(tree: &T, node: T::NodeId) -> TableRow<T::NodeId> {
    let mut row = TableRow { node: Some(node), cells: Vec::new() };
    for child in tree.children(node) {
        if tree.table_role(child) == TableRole::Cell {
            row.cells.push(build_source_cell(tree, child));
        }
    }
    row
}

fn build_source_cell<T: TableTree>(tree: &T, node: T::NodeId) -> SourceCell<T::NodeId> {
    let colspan = tree.attr_usize(node, "colspan").unwrap_or(1).max(1);
    let rowspan = tree.attr_usize(node, "rowspan").unwrap_or(1).max(1);
    SourceCell { node, colspan, rowspan }
}

/// Returns the last anonymous body group, creating one if needed.
fn anon_body_group<N>(groups: &mut Vec<RowGroup<N>>) -> &mut RowGroup<N> {
    if groups.last().map(|g| g.node.is_none()).unwrap_or(false) {
        groups.last_mut().expect("existence confirmed above")
    } else {
        groups.push(RowGroup { node: None, rows: Vec::new() });
        groups.last_mut().expect("just pushed")
    }
}

/// Returns the last anonymous row in `rows`, creating one if needed.
fn anon_row<N>(rows: &mut Vec<TableRow<N>>) -> &mut TableRow<N> {
    if rows.last().map(|r| r.node.is_none()).unwrap_or(false) {
        rows.last_mut().expect("existence confirmed above")
    } else {
        rows.push(TableRow { node: None, cells: Vec::new() });
        rows.last_mut().expect("just pushed")
    }
}

fn parse_table_sizing<T: TableTree>(tree: &T, node: T::NodeId) -> TableSizing {
    match tree.css_length(node, CssProp::TableLayout) {
        // We use Px(1.0) as "fixed" sentinel — implementors should use this convention.
        CssLength::Px(v) if v == 1.0 => TableSizing::Fixed,
        _ => TableSizing::Auto,
    }
}

fn parse_border_collapse<T: TableTree>(tree: &T, node: T::NodeId) -> BorderCollapse {
    match tree.css_length(node, CssProp::BorderCollapse) {
        // Px(1.0) = collapse sentinel
        CssLength::Px(v) if v == 1.0 => BorderCollapse::Collapse,
        _ => BorderCollapse::Separate,
    }
}

fn parse_border_spacing<T: TableTree>(tree: &T, node: T::NodeId) -> (f32, f32) {
    let x = tree.css_length(node, CssProp::BorderSpacingX).px_or(2.0);
    let y = tree.css_length(node, CssProp::BorderSpacingY).px_or(2.0);
    (x, y)
}
