use crate::types::{BorderCollapse, CssLength, CssProp, TableRole, TableSizing};
use crate::TableTree;

/// Fully parsed table structure, typed by section kind.
pub struct TableModel<N> {
    pub node: N,
    pub caption: Option<N>,
    pub column_groups: Vec<ColGroup<N>>,
    /// Rows from `<thead>` / `display: table-header-group` elements, in source order.
    pub header_groups: Vec<RowGroup<N>>,
    /// Rows from `<tbody>` / `display: table-row-group` elements, in source order.
    pub row_groups: Vec<RowGroup<N>>,
    /// Rows from `<tfoot>` / `display: table-footer-group` elements, in source order.
    pub footer_groups: Vec<RowGroup<N>>,
    pub sizing: TableSizing,
    pub border_collapse: BorderCollapse,
    /// `border-spacing` horizontal and vertical values in pixels.
    pub border_spacing: (f32, f32),
}

pub struct ColGroup<N> {
    pub node: N,
    pub columns: Vec<N>,
}

pub struct RowGroup<N> {
    /// `None` for anonymous groups generated by the algorithm.
    pub node: Option<N>,
    pub rows: Vec<TableRow<N>>,
}

pub struct TableRow<N> {
    /// `None` for anonymous rows generated by the algorithm.
    pub node: Option<N>,
    pub cells: Vec<SourceCell<N>>,
}

/// A cell as read directly from the source tree, before grid placement.
pub struct SourceCell<N> {
    pub node: N,
    /// Effective colspan (always >= 1).
    pub colspan: usize,
    /// Effective rowspan (always >= 1, clamped per section by the grid builder).
    pub rowspan: usize,
}

/// Walk `tree` starting from `table_node` and build the typed `TableModel`.
///
/// Anonymous row groups and rows are generated where the CSS spec requires them
/// (§17.2.1): a bare `Row` directly under the table becomes a body row group;
/// a bare `Cell` directly under a row group becomes an anonymous row.
pub fn build_model<T: TableTree>(tree: &T, table_node: T::NodeId) -> TableModel<T::NodeId> {
    let mut model = TableModel {
        node: table_node,
        caption: None,
        column_groups: Vec::new(),
        header_groups: Vec::new(),
        row_groups: Vec::new(),
        footer_groups: Vec::new(),
        sizing: parse_table_sizing(tree, table_node),
        border_collapse: parse_border_collapse(tree, table_node),
        border_spacing: parse_border_spacing(tree, table_node),
    };

    // Consecutive non-table children share one anonymous cell, so only the first of a run
    // opens one; the rest are already inside it.
    let mut in_anonymous_run = false;

    for child in tree.children(table_node) {
        match tree.table_role(child) {
            TableRole::Caption => {
                if model.caption.is_none() {
                    model.caption = Some(child);
                }
            }
            TableRole::ColumnGroup => {
                model.column_groups.push(build_col_group(tree, child));
            }
            TableRole::HeaderGroup => {
                model.header_groups.push(build_row_group(tree, child));
            }
            TableRole::RowGroup => {
                model.row_groups.push(build_row_group(tree, child));
            }
            TableRole::FooterGroup => {
                model.footer_groups.push(build_row_group(tree, child));
            }
            // Bare row directly inside the table → anonymous tbody
            TableRole::Row => {
                let group = anon_body_group(&mut model.row_groups);
                group.rows.push(build_row(tree, child));
            }
            // Bare cell directly inside the table → anonymous row inside anonymous tbody
            TableRole::Cell => {
                let group = anon_body_group(&mut model.row_groups);
                let row = anon_row(&mut group.rows);
                row.cells.push(build_source_cell(tree, child));
            }
            // Content that is not part of the table structure: CSS 2.1 §17.2.1 wraps each
            // consecutive run of it in one anonymous cell, inside an anonymous row and body
            // group. That is what makes `display: table` usable as a plain shrink-to-fit box -
            // Wikipedia thumbnails are `figure { display: table }` around a link and a caption,
            // and without the fixup such a table has no columns at all and computes to 0x0.
            //
            // An anonymous cell has no node of its own, and the layout tree is addressed by
            // node, so the run's first child stands in for it. That is exact for a run of one,
            // which is the shape that occurs in practice.
            //
            // KNOWN LIMIT: for a longer run only that first child is measured and positioned by
            // the table - the rest keep whatever the layout engine gave them inside the table's
            // box. Representing the whole run needs either a synthetic node id, which the
            // `TableTree` contract has no way to mint, or a cell that carries several nodes.
            TableRole::Other => {
                let group = anon_body_group(&mut model.row_groups);
                let row = anon_row(&mut group.rows);
                if in_anonymous_run {
                    continue;
                }
                row.cells.push(SourceCell {
                    node: child,
                    colspan: 1,
                    rowspan: 1,
                });
                in_anonymous_run = true;
                continue;
            }
            TableRole::Table | TableRole::Column => {}
        }
        in_anonymous_run = false;
    }

    model
}

fn build_col_group<T: TableTree>(tree: &T, node: T::NodeId) -> ColGroup<T::NodeId> {
    let mut group = ColGroup {
        node,
        columns: Vec::new(),
    };
    for child in tree.children(node) {
        if tree.table_role(child) == TableRole::Column {
            group.columns.push(child);
        }
    }
    group
}

fn build_row_group<T: TableTree>(tree: &T, node: T::NodeId) -> RowGroup<T::NodeId> {
    let mut group = RowGroup {
        node: Some(node),
        rows: Vec::new(),
    };
    for child in tree.children(node) {
        match tree.table_role(child) {
            TableRole::Row => group.rows.push(build_row(tree, child)),
            // Cell directly inside row group → anonymous row
            TableRole::Cell => {
                let row = anon_row(&mut group.rows);
                row.cells.push(build_source_cell(tree, child));
            }
            _ => {}
        }
    }
    group
}

fn build_row<T: TableTree>(tree: &T, node: T::NodeId) -> TableRow<T::NodeId> {
    let mut row = TableRow {
        node: Some(node),
        cells: Vec::new(),
    };
    for child in tree.children(node) {
        if tree.table_role(child) == TableRole::Cell {
            row.cells.push(build_source_cell(tree, child));
        }
    }
    row
}

fn build_source_cell<T: TableTree>(tree: &T, node: T::NodeId) -> SourceCell<T::NodeId> {
    let colspan = tree.attr_usize(node, "colspan").unwrap_or(1).max(1);
    let rowspan = tree.attr_usize(node, "rowspan").unwrap_or(1).max(1);
    SourceCell { node, colspan, rowspan }
}

/// Returns the last anonymous body group, creating one if needed.
fn anon_body_group<N>(groups: &mut Vec<RowGroup<N>>) -> &mut RowGroup<N> {
    if groups.last().map(|g| g.node.is_none()).unwrap_or(false) {
        groups.last_mut().unwrap_or_else(|| unreachable!())
    } else {
        groups.push(RowGroup {
            node: None,
            rows: Vec::new(),
        });
        groups.last_mut().unwrap_or_else(|| unreachable!())
    }
}

/// Returns the last anonymous row in `rows`, creating one if needed.
fn anon_row<N>(rows: &mut Vec<TableRow<N>>) -> &mut TableRow<N> {
    if rows.last().map(|r| r.node.is_none()).unwrap_or(false) {
        rows.last_mut().unwrap_or_else(|| unreachable!())
    } else {
        rows.push(TableRow {
            node: None,
            cells: Vec::new(),
        });
        rows.last_mut().unwrap_or_else(|| unreachable!())
    }
}

fn parse_table_sizing<T: TableTree>(tree: &T, node: T::NodeId) -> TableSizing {
    match tree.css_length(node, CssProp::TableLayout) {
        // We use Px(1.0) as "fixed" sentinel - implementors should use this convention.
        CssLength::Px(1.0) => TableSizing::Fixed,
        _ => TableSizing::Auto,
    }
}

fn parse_border_collapse<T: TableTree>(tree: &T, node: T::NodeId) -> BorderCollapse {
    match tree.css_length(node, CssProp::BorderCollapse) {
        // Px(1.0) = collapse sentinel
        CssLength::Px(1.0) => BorderCollapse::Collapse,
        _ => BorderCollapse::Separate,
    }
}

fn parse_border_spacing<T: TableTree>(tree: &T, node: T::NodeId) -> (f32, f32) {
    let x = tree.css_length(node, CssProp::BorderSpacingX).px_or(2.0);
    let y = tree.css_length(node, CssProp::BorderSpacingY).px_or(2.0);
    (x, y)
}
